### ISSUE TITLE
Add default post routing

### ISSUE THREAD

**Issue by etheya** [wolfendale/prototype_kit#10]

**Comment by wolfendale** [comment]
This is in reference to the routing @LukeDeighton has done for one of the existing prototypes. Would be good to get a link to the repo (although it'll be internal github so maybe we can't :/)

If that's the case I'll pick this up

**Comment by wolfendale** [comment]
[Added](https://github.com/wolfendale/prototype_kit/commit/0ef6d0ad6d095da88a4df1978be1d238e636b5df)

**Comment by etheya** [comment]
Nice one, glad we could make use of that too
