### ISSUE TITLE
Folder naming...

### ISSUE THREAD

**Issue by etheya** [wolfendale/prototype_kit#14]
Having just been and edited an iteration from Sprint0 to something more tangible, i noticed that the folder name in the structure still remained the same, this could become an issue if people rename one of the iterations and then become confused? 

Im sure this is not a problem if you create something, but it would seem pointless to have the option to EDIT if we can't then change the name of the folder too?

**Comment by wolfendale** [comment]
The folder name is the 'path' rather than the name itself, having this separation lets us have names that have a structure that would not be valid for a file system, it also lets us not worry about OS specific behaviour in this regard.

That said, it's totally possible for us to add a 'path' field in the edit iteration window, I just didn't at the time ;)

**Comment by etheya** [comment]
I think I've added a path field in now... but i might be wrong will check..

**Comment by etheya** [comment]
Yes i added the path field in on EDIT... but it currently doesn't allow for the change in the folder.. although that might be as something else needs changing too.

**Comment by etheya** [comment]
I think this would be good to add in, as ive just come up with this issues whilst using on a service... i want to rename the PATH... but i cant do that. If i rename the folder itself then i then get issues with it not working. I think we should have this but put in the help text for creating the path name.

**Comment by wolfendale** [comment]
Does it still not work even when you restart the application?

**Comment by roblav** [comment]
I've added this functionality and issued a pull request. 
Do we want some validation on the input field?
Also, I noticed that the iteration name and link don't update on the home page until the page is refreshed.

**Comment by etheya** [comment]
No it didn't work with restart either..

**Comment by roblav** [comment]
I just noticed the message at the bottom of the home page 'You will need to refresh the page to see your changes after editing or creating new iteration.'

**Comment by etheya** [comment]
Newbie error :)

**Comment by wolfendale** [comment]
This is because of the hacky nature of the method we use to restart the app when changes are made ;) would like to address this in the future.

**Comment by roblav** [comment]
This was fixed and tested.
