### ISSUE TITLE
Find a way to include govuk_elements as a dependency

### ISSUE THREAD

**Issue by wolfendale** [wolfendale/prototype_kit#3]
Currently we have some files from govuk_elements included as part of the project, it'd be much better if we could have them included as a dependency in NPM.

I did some initial looking into this and tried adding it as a github dependency in NPM but it failed to checkout (I'm developing on a windows machine and that may be something to do with it!)

Would be good if this could be looked into and fixed (preferrably in a way that works across all dev platforms)

**Comment by rpowis** [comment]
govuk

**Comment by wolfendale** [comment]
This has been completed
