### ISSUE TITLE
Admin functions visibility

### ISSUE THREAD

**Issue by etheya** [wolfendale/prototype_kit#4]
Just thinking do we need to somehow show/hide the visibility of the Admin functionality since this can be seen eventually on herokuapp or even by BA's and so on so that people are not adding new sprints or messing with things un-expectedly.

**Comment by wolfendale** [comment]
I've raised an issue about this [here](https://github.com/wolfendale/prototype_kit/issues/8) The idea is that the admin functionality will only be shown/be accessible locally and once deployed to heroku it will not be accessible.
