### ISSUE TITLE
Admin contained within own section

### ISSUE THREAD

**Issue by etheya** [wolfendale/prototype_kit#5]
Possibly we should put the admin functionality behind a link or something so that its contained in one page?

**Comment by wolfendale** [comment]
This would be really easy for us to do, technically the Admin stuff is already separated from the rest, but if you can think of how you would like it displayed we can easily change it :)

**Comment by etheya** [comment]
Yeah i thought i can sort the view of this sort of thing out as long as i know we can technically do it without too much of a problem

**Comment by wolfendale** [comment]
You should just be able to edit the views in the global and/or global/admin sections. If you need any help with this let me know, I'll set this as an enhancement and will close it when you submit a PR for it.

**Comment by etheya** [comment]
Ok looking at this now.
