### ISSUE TITLE
Ability to add service name/alpha banner?

### ISSUE THREAD

**Issue by etheya** [wolfendale/prototype_kit#6]
Be nice in the admin to allow for someone to add the service name and/or alpha banner etc without messing in the code? not a big deal but would be a nice little simple feature to keep this implemented correctly... simple radio button or dropdown choice maybe?

**Comment by wolfendale** [comment]
Sounds like a good idea, do you see this being on an iteration-by-iteration level? So it could be a radio group on the create/edit iteration form?

**Comment by etheya** [comment]
Yeah something like that... that way as the prototype develops and iterates it could be that they move into various phases... anything we can simplify and make easier for UI/UX then i think its a good move.. this wont change massively either, but with it been an include or piece of text that changes i thought it would be an easy addition/feature.

**Comment by wolfendale** [comment]
I think that's fair. I'd be happy for anyone to take this up, otherwise I'll get to it eventually ;)

**Comment by wolfendale** [comment]
[Added](https://github.com/wolfendale/prototype_kit/commit/2bbeeabe4e16e32110723d9376ff938af288ae7e)
