### ISSUE TITLE
Environment Check

### ISSUE THREAD

**Issue by wolfendale** [wolfendale/prototype_kit#8]
We need to add an environment check so that certain features are disabled when an app is deployed to Heroku. (We should also have auth set up for heroku deploy)

In order for this to work as it stands, we should use an environment variable (NODE_ENV I believe is set by Heroku automatically) to determine whether we are running locally or in heroku. We need to make sure that the admin application is only mounted conditionally when this environment variable is not set.

We also need to make a change in the admin-tools include to that it is hidden when in a production deployment. This will require a variable passed to the render in both the global application, admin application and the subapps. (This could be done ideally as adding an app.locals var in the start.js and subapp.js modules)

Sorry for this rambling train-of-thought issue!

**Comment by wolfendale** [comment]
[Added](https://github.com/wolfendale/prototype_kit/commit/ea9bd3aba47e407ad085ee5b33239b7d5de38408)

**Comment by etheya** [comment]
Very nice that.
